---
name: Atul Build Java application
on: 
 workflow_dispatch:
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
     - name: clone the repo
       uses : actions/checkout@v4
     - name: install java 17
       uses : actions/setup-java@v4
       with:
        java-version: "17"
        distribution : "temurin"
        catch : maven
     - name : Build Java code
       run : mvn clean install package
       
       
